### ISSUE TITLE
No idea what this is but it doesn't build anymore :(

### ISSUE THREAD

**Issue by JonathanSeriesX** [Coayer/thereGoesAnAirplane#1]
Hi!

So I've found this in bookmarks, saved a couple of years ago

Tried command from readme.md, but it failed on OrbStack / arm64 with:

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.getCookie()
	/build/main.go:60 +0x1d4
main.init()
	/build/main.go:14 +0x20
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.getCookie()
	/build/main.go:60 +0x1d4
main.init()
	/build/main.go:14 +0x20
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.getCookie()
	/build/main.go:60 +0x1d4
main.init()
	/build/main.go:14 +0x20

```

Should we expect an update to this app? Thanks.

**Comment by Coayer** [comment]
Hey, the README is very lacking – I wrote this so I could query flightradar24.com (an ADS-B aircraft data tracking website) via a Siri shortcut to find out what plane is flying overhead. It was broken for me but I hadn't got round to checking why. The problem is that flightradar24 has switched to using web gRPC which is completely different from the REST JSON API this project was written around. Unfortunately I'm not going to update it for this change so I'll have to archive the project. If you're in the US, I think Siri already has built-in plane tracking.
